const Map<String, String> FRAMESv2_3 = {
  'AENC': 'Encryption',
  'APIC': 'APIC',
  'COMM': 'Comment',
  'COMR': 'Commercial',
  'ENCR': 'ENCR',
  'EQUA': 'Equalization',
  'ETCO': 'ETCO',
  'GEOB': 'GEOB',
  'GRID': 'GRID',
  'IPLS': 'People',
  'LINK': 'Information',
  'MCDI': 'MCDI',
  'MLLT': 'MLLT',
  'OWNE': 'OWNE',
  'PRIV': 'PRIV',
  'PCNT': 'PlayCounter',
  'POPM': 'Popularimeter',
  'POSS': 'POSS',
  'RBUF': 'RBUF',
  'RVAD': 'RVAD',
  'SYLT': 'Lyrics',
  'SYTC': 'SYTC',
  'TALB': 'Album',
  'TBPM': 'BPM',
  'TCOM': 'Composer',
  'TCON': 'Genre',
  'TCOP': 'Copyright',
  'TDAT': 'Date',
  'TDLY': 'Playlist',
  'TENC': 'EncodedBy',
  'TEXT': 'Lyricist',
  'TFLT': 'FileType',
  'TIME': 'Time',
  'TIT1': 'Content',
  'TIT2': 'Title',
  'TIT3': 'SubTitle',
  'TKEY': 'Key',
  'TLAN': 'Language',
  'TLEN': 'Length',
  'TMED': 'MediaType',
  'TOAL': 'OriginalAlbum',
  'TOFN': 'OriginalFilename',
  'TOLY': 'OriginalLyricist',
  'TOPE': 'OriginalPerformer',
  'TORY': 'OriginalReleaseYear',
  'TOWN': 'Owner',
  'TPE1': 'Artist',
  'TPE2': 'Accompaniment',
  'TPE3': 'Conductor',
  'TPE4': 'ModifiedBy',
  'TPOS': 'TPOS',
  'TPUB': 'Publisher',
  'TRCK': 'Track',
  'TRDA': 'RecordedOn',
  'TRSN': 'RadioStation',
  'TRSO': 'RadioStationOwner',
  'TSIZ': 'Size',
  'TSRC': 'ISRC',
  'TSSE': 'Settings',
  'TYER': 'Year',
  'TXXX': 'AdditionalInfo',
  'UFID': 'ID',
  'USER': 'Terms',
  'USLT': 'UnsyncTranscript',
  'WCOM': 'CommercialInfo',
  'WCOP': 'CopyrightInfo',
  'WOAF': 'OFileWebpage',
  'WOAR': 'OArtistWebpage',
  'WOAS': 'OAudioWebpage',
  'WORS': 'ORadioWebpage',
  'WPAY': 'Payment',
  'WPUB': 'OPublisherWebpage',
  'WXXX': 'CLink'
};

const GENREv1 = [
  'Blues',
  'Classic Rock',
  'Country',
  'Dance',
  'Disco',
  'Funk',
  'Grunge',
  'Hip-Hop',
  'Jazz',
  'Metal',
  'New Age',
  'Oldies',
  'Other',
  'Pop',
  'Rhythm and Blues',
  'Rap',
  'Reggae',
  'Rock',
  'Techno',
  'Industrial'
      'Alternative',
  'Ska',
  'Death Metal',
  'Pranks',
  'Soundtrack',
  'Euro-Techno',
  'Ambient',
  'Trip-Hop',
  'Vocal',
  'Jazz & Funk',
  'Fusion',
  'Trance',
  'Classical',
  'Instrumental',
  'Acid',
  'House',
  'Game',
  'Sound clip',
  'Gospel',
  'Noise',
  'Alternative Rock',
  'Bass',
  'Soul',
  'Punk',
  'Space',
  'Meditative',
  'Instrumental Pop',
  'Instrumental Rock',
  'Ethnic',
  'Gothic',
  'Darkwave',
  'Techno-Industrial',
  'Electronic',
  'Pop-Folk',
  'Eurodance',
  'Dream',
  'Southern Rock',
  'Comedy',
  'Cult',
  'Gangsta',
  'Top 40',
  'Christian Rap',
  'Pop/Funk',
  'Jungle music',
  'Native US',
  'Cabaret',
  'New Wave',
  'Psychedelic',
  'Rave',
  'Showtunes',
  'Trailer',
  'Lo-Fi',
  'Tribal',
  'Acid Punk',
  'Acid Jazz',
  'Polka',
  'Retro',
  'Musical',
  'Rock ’n’ Roll,'
      'Hard Rock'
];
